spring:
  datasource:
    url: jdbc:oracle:thin:@${DB_HOST:uat-db-server}:${DB_PORT:1521}:${DB_SID:UAT}
    driver-class-name: oracle.jdbc.OracleDriver
    username: ${DB_USERNAME:exception_workflow_uat}
    password: ${DB_PASSWORD:uat_password}
  
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: false
        envers:
          store_data_at_delete: true
          audit_table_suffix: _AUD

server:
  port: 8080
